# 붓꽃 분류(Naive Bayes)
- 통계적 분류기
- 주어진 데이터가 특정 클래스에 속하는지를 조건부 확률을 통해서 예측
- 텍스트 데이터처럼 희소한 고차원인 경우, 높은 정확도와 속도를 제공
- 적용 분야: 스팸 메일 분류, 문서 주제 분류, 네트워크 침입자 분류

## 패키지 로딩

In [26]:
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB    # 독립변수가 연속형인 경우 시용,  범주형 multi
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

## 데이터 로딩 및 분할

In [3]:
x, y = load_iris(return_X_y=True)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=10, stratify=y)

## 모델 생성

In [4]:
model = GaussianNB()
model.fit(x_train, y_train)

GaussianNB()

## 모델 평가

In [5]:
y_hat = model.predict(x_test)
print(f'정확도:{accuracy_score(y_test, y_hat)}')

정확도:1.0


In [7]:
print(confusion_matrix(y_test, y_hat))

[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


# [문제] 독버섯 분류하기

## 패키지 로딩

In [56]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score

In [86]:
df = pd.read_csv('./dataset/mushrooms.csv')
print(df.shape)
display(df.head())
print(df['type'].value_counts())
df.info()

(8124, 23)


type cap_shape cap_surface cap_color bruises     odor gill_attachment  \
0  poisonous    convex      smooth     brown     yes  pungent            free   
1     edible    convex      smooth    yellow     yes   almond            free   
2     edible      bell      smooth     white     yes    anise            free   
3  poisonous    convex       scaly     white     yes  pungent            free   
4     edible    convex      smooth      gray      no     none            free   

  gill_spacing gill_size gill_color  ... stalk_surface_below_ring  \
0        close    narrow      black  ...                   smooth   
1        close     broad      black  ...                   smooth   
2        close     broad      brown  ...                   smooth   
3        close    narrow      brown  ...                   smooth   
4      crowded     broad      black  ...                   smooth   

  stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
0                  white                  white   partial      white   
1                  white                  white   partial      white   
2                  white                  white   partial      white   
3                  white                  white   partial      white   
4                  white                  white   partial      white   

  ring_number   ring_type spore_print_color population  habitat  
0         one     pendant             black  scattered    urban  
1         one     pendant             brown   numerous  grasses  
2         one     pendant             brown   numerous  meadows  
3         one     pendant             black  scattered    urban  
4         one  evanescent             brown   abundant  grasses  

[5 rows x 23 columns]

type
edible       4208
poisonous    3916
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   type                      8124 non-null   object
 1   cap_shape                 8124 non-null   object
 2   cap_surface               8124 non-null   object
 3   cap_color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill_attachment           8124 non-null   object
 7   gill_spacing              8124 non-null   object
 8   gill_size                 8124 non-null   object
 9   gill_color                8124 non-null   object
 10  stalk_shape               8124 non-null   object
 11  stalk_root                8124 non-null   object
 12  stalk_surface_above_ring  8124 non-null   object
 13  stalk_surfa

## 데이터 분리 및 인코딩

### 라벨 인코딩

In [71]:
from sklearn.preprocessing import LabelEncoder

df = df.apply(lambda col:LabelEncoder().fit_transform(col))  # lambda col = df의 column 값 (시리즈 객체)

In [72]:
x = df.drop('type', axis=1)
y = df['type']

### 원-핫 인코딩

In [87]:
x = df.drop('type', axis=1)
x = pd.get_dummies(x)    # 독립변수 x에 대해서는 원-핫
y = df['type']
y = y.map({'edible':0, 'poisonous':1})  # 종속변수 y에 대해서는 라벨 인코딩

In [88]:
print(x.shape)

(8124, 117)


In [90]:
display(x.head())

cap_shape_bell  cap_shape_conical  cap_shape_convex  cap_shape_flat  \
0           False              False              True           False   
1           False              False              True           False   
2            True              False             False           False   
3           False              False              True           False   
4           False              False              True           False   

   cap_shape_knobbed  cap_shape_sunken  cap_surface_fibrous  \
0              False             False                False   
1              False             False                False   
2              False             False                False   
3              False             False                False   
4              False             False                False   

   cap_surface_grooves  cap_surface_scaly  cap_surface_smooth  ...  \
0                False              False                True  ...   
1                False              False                True  ...   
2                False              False                True  ...   
3                False               True               False  ...   
4                False              False                True  ...   

   population_scattered  population_several  population_solitary  \
0                  True               False                False   
1                 False               False                False   
2                 False               False                False   
3                  True               False                False   
4                 False               False                False   

   habitat_grasses  habitat_leaves  habitat_meadows  habitat_paths  \
0            False           False            False          False   
1             True           False            False          False   
2            False           False             True          False   
3            False           False            False          False   
4             True           False            False          False   

   habitat_urban  habitat_waste  habitat_woods  
0           True          False          False  
1          False          False          False  
2          False          False          False  
3           True          False          False  
4          False          False          False  

[5 rows x 117 columns]

In [94]:
# 학습/평가 데이터 바꿈
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=10, stratify=y)

## 모델 생성

In [95]:
model = MultinomialNB()
model.fit(x_train, y_train)

MultinomialNB()

## 모델 평가

In [96]:
y_hat = model.predict(x_test)
print(confusion_matrix(y_test, y_hat))

[[841   1]
 [ 74 709]]


In [97]:
print(f'정확도:{accuracy_score(y_test, y_hat):.3f}')
print(f'AUC:{roc_auc_score(y_test, model.predict_proba(x_test)[:,1]):.3f}')

정확도:0.954
AUC:0.997
